name: Serenity BDD Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MAVEN_IMAGE: maven:3.9.4-eclipse-temurin-21
      APP_DIR: /app
      BASE_URL: https://waarkoop-server.herokuapp.com/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      env:
        FINAL_BASE_URL: ${{ vars.BASE_URL || env.BASE_URL }}
        FINAL_APP_DIR: ${{ vars.APP_DIR || env.APP_DIR }}
        FINAL_MAVEN_IMAGE: ${{ vars.MAVEN_IMAGE || env.MAVEN_IMAGE }}
      run: |
        docker build \
          --build-arg MAVEN_IMAGE=${{ env.FINAL_MAVEN_IMAGE }} \
          --build-arg APP_DIR=${{ env.FINAL_APP_DIR }} \
          --build-arg BASE_URL=${{ env.FINAL_BASE_URL }} \
          -t serenity-tests .

    - name: Run Serenity tests + reports inside container
      run: |
        docker run --name serenity-tests-container serenity-tests \
          bash -c "mvn clean install spotbugs:check -Dspotbugs.failOnError=true -Drestapi.baseurl=$BASE_URL; mvn serenity:aggregate"

    - name: Copy Serenity reports
      if: always()
      run: |
        mkdir -p ./target/site ./target/failsafe-reports
        docker cp serenity-tests-container:/app/target/site/serenity ./target/site/serenity
        docker cp serenity-tests-container:/app/target/failsafe-reports ./target/failsafe-reports

    - name: Cleanup container
      if: always()
      run: |
        docker rm -f serenity-tests-container || true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: serenity-reports
        path: |
          target/site/serenity/
          target/failsafe-reports/
        retention-days: 30

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/serenity
        destination_dir: serenity-reports
        force_orphan: true

    - name: Comment PR with report link
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request' && success()
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 📊 Serenity Test Reports

            The test reports are available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/

            - 📈 [Full Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/index.html)
            - 🎯 [Requirements Coverage](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/requirements.html)
            - 🧪 [Test Results](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/capabilities.html)`
          })
