name: Serenity BDD Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t serenity-tests .
        
    - name: Run Serenity tests in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/target:/app/target \
          serenity-tests \
          mvn clean verify -Drestapi.baseurl=https://waarkoop-server.herokuapp.com/
      continue-on-error: true  # Continue even if tests fail to generate reports
      
    - name: Generate Serenity reports
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/target:/app/target \
          serenity-tests \
          mvn serenity:aggregate
      if: always()  # Always generate reports
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: serenity-reports
        path: |
          target/site/serenity/
          target/failsafe-reports/
        retention-days: 30
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/serenity
        destination_dir: serenity-reports
        force_orphan: true
        
    - name: Comment PR with report link
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request' && always()
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ## 📊 Serenity Test Reports
            
            The test reports are available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/
            
            - 📈 [Full Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/index.html)
            - 🎯 [Requirements Coverage](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/requirements.html)
            - 🧪 [Test Results](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/serenity-reports/capabilities.html)
          })
